Repository laminas/laminas-servicemanager, pull requests merged in 2022-06, with the labels that each got.

#137 Improve type inference for plugin manager implementations
  psalm-baseline.xml
  src/AbstractPluginManager.php
  src/PluginManagerInterface.php
  src/ServiceLocatorInterface.php
  src/ServiceManager.php
Labels: Documentation, Enhancement

#133 Fixed namespace generation in `FactoryCreator` utility
  src/Tool/FactoryCreator.php
  test/Tool/FactoryCreatorTest.php
Labels: Bug

#140 GITIGNORE: Add .phpbench directory
  .gitignore
Labels: Enhancement

#141 Skip `class_alias()` declarations when interfaces were already declared, allowing for usage with preloading
  src/autoload.php
Labels: Enhancement
